### ISSUE TITLE
Automagic installation through Arduino Board Manager gets 403 Forbidden

### ISSUE THREAD

**Issue by evanrinehart** [Controllino/ControllinoHardware#4]
Following the guide here for installing Controllino support in the Arduino IDE
http://controllino.biz/wp-content/uploads/2016/04/Detailed-STEP-BY-STEP-GUIDE-FOR-CONTROLLINO-INSTALLATION.pdf

The ControllinoHW.zip file is perfectly downloadable at
http://controllino.biz/download/ControllinoHW.zip

Note this is Arduino IDE for OSX.

However the download inside the IDE when you press Install gives the following failure to download:

```
Error downloading http://controllino.biz/download/ControllinoHW.zip
java.lang.RuntimeException: java.lang.Exception: Error downloading http://controllino.biz/download/ControllinoHW.zip
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$4.run(ContributionManagerUI.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Error downloading http://controllino.biz/download/ControllinoHW.zip
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:100)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:63)
	at cc.arduino.contributions.packages.ContributionInstaller.install(ContributionInstaller.java:104)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI$4.run(ContributionManagerUI.java:176)
	... 1 more
Caused by: java.io.IOException: Recevied invalid http status code from server: 403
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:160)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:98)
	... 4 more
```

**Comment by egarl004** [comment]
I got this error only on arduino ide 1.6.11
Older versions, in my case 1.6.8, worked fine.

**Comment by evanrinehart** [comment]
Yes! I upgraded to Arduino IDE 1.8.1 and it downloaded. Thanks.
